name: tfmermaid example
on:
  push:

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      - uses: ./
        with:
          file: ${{ github.workspace }}/README.md
          label: linux-vm
          orientation: TB
          working-directory: linux-vm

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: README.md

      - name: commit
        if: always()
        run: |
          git add README.md
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "generated" -m "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            git push https://sb185296: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@github.com/sb185296/tfmermaid-action.git
          
