name: tfmermaid example
on:
  push:

jobs:
  example:
    runs-on: ubuntu-latest
    env:
      TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: hashicorp/terraform-provider-aws
          path: terraform-provider-aws
      - uses: actions/checkout@v3
        with:
          repository: hashicorp/terraform-provider-google
          path: terraform-provider-google
      - uses: actions/checkout@v3
        with:
          repository: hashicorp/terraform-provider-azurerm
          path: terraform-provider-azurerm
      - run: mkdir -p $TF_PLUGIN_CACHE_DIR
      - uses: ./
        with:
          file: ${{ github.workspace }}/README.md
          label: terraform-provider-azurerm/examples/api-management
          orientation: TB
          working-directory: ./terraform-provider-azurerm/examples/api-management
      - uses: ./
        with:
          file: ${{ github.workspace }}/README.md
          label: terraform-provider-azurerm/examples/recovery-services/virtual-machine
          working-directory: ./terraform-provider-azurerm/examples/recovery-services/virtual-machine
      - uses: ./
        with:
          file: ${{ github.workspace }}/README.md
          label: terraform-provider-azurerm/examples/traffic-manager/vm-scale-set
          working-directory: ./terraform-provider-azurerm/examples/traffic-manager/vm-scale-set
      - run: sudo apt install graphviz
      - run: terraform graph | dot -Tsvg > ../../../graph.svg
        working-directory: ./terraform-provider-aws/examples/two-tier

      - name: comment PR
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: README.md

      - name: commit
        run: |

          git add README.md
          if ! git diff --cached --quiet --exit-code
          then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "generated" -m "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            git push
          fi
