name: tfmermaid example
on:
  push:

jobs:
  example:
    runs-on: ubuntu-latest
    env:
      TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - run: mkdir -p $TF_PLUGIN_CACHE_DIR
      - uses: ./
        with:
          file: ${{ github.workspace }}/README.md
          label: linux-vm
          orientation: TB
          working-directory: linux-vm


      - name: commit
        run: |
          git add README.md
          if ! git diff --cached --quiet --exit-code
          then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "generated" -m "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            git push
          fi
